/**
 * JARVIS document forge — turns AI-generated content into real files.
 *
 *   PDF    → jsPDF (multi-page, wrapped text, headings)
 *   Word   → docx  (Paragraph/Heading structures, .docx)
 *   Excel  → xlsx  (markdown tables become sheets; text falls back to a column)
 *   Markdown / plain text → raw blob download
 *
 * The exporter detects structure in the assistant's answer:
 *   "# Heading" lines, "- " / "1. " lists, and | markdown | tables.
 */

import { jsPDF } from "jspdf";
import { Document, Packer, Paragraph, HeadingLevel, TextRun } from "docx";
import * as XLSX from "xlsx";

export type ExportFormat = "pdf" | "docx" | "xlsx" | "md" | "txt";

interface Block {
  kind: "heading" | "para" | "list" | "table";
  text: string;
  rows?: string[][];
}

/** Parse markdown-ish AI output into structural blocks. */
export function parseBlocks(content: string): Block[] {
  const lines = content.split("\n");
  const blocks: Block[] = [];
  let para: string[] = [];
  let list: string[] = [];
  let table: string[][] = [];

  const flush = () => {
    if (para.length) {
      blocks.push({ kind: "para", text: para.join(" ").trim() });
      para = [];
    }
    if (list.length) {
      blocks.push({ kind: "list", text: list.join("\n") });
      list = [];
    }
    if (table.length) {
      blocks.push({ kind: "table", text: "", rows: table });
      table = [];
    }
  };

  for (const raw of lines) {
    const line = raw.trimEnd();
    const heading = /^(#{1,3})\s+(.*)$/.exec(line);
    const tableLine = /^\s*\|(.+)\|\s*$/.exec(line);
    const listLine = /^\s*(?:[-*•]|\d+[.)])\s+(.*)$/.exec(line);

    if (heading) {
      flush();
      blocks.push({ kind: "heading", text: heading[2] });
    } else if (tableLine && !tableLine[1].match(/^[\s:-]+$/)) {
      flushParaAndList();
      table.push(tableLine[1].split("|").map((c) => c.trim()));
    } else if (listLine) {
      flushParaOnly();
      list.push(`• ${listLine[1]}`);
    } else if (!line.trim()) {
      flush();
    } else {
      flushListOnly();
      para.push(line.trim());
    }
  }
  flush();
  return blocks;

  function flushParaOnly() {
    if (para.length) {
      blocks.push({ kind: "para", text: para.join(" ").trim() });
      para = [];
    }
  }
  function flushListOnly() {
    if (list.length) {
      blocks.push({ kind: "list", text: list.join("\n") });
      list = [];
    }
  }
  function flushParaAndList() {
    flushParaOnly();
    flushListOnly();
  }
}

function stripMd(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`{1,3}([^`]*)`{1,3}/g, "$1")
    .replace(/\[(.+?)\]\((.+?)\)/g, "$1 ($2)");
}

function safeName(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "jarvis-document"
  );
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

// ── PDF ──────────────────────────────────────────────────────────────────────

function exportPdf(content: string, title: string): void {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 52;
  const width = pdf.internal.pageSize.getWidth() - margin * 2;
  const height = pdf.internal.pageSize.getHeight();
  let y = margin;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.setTextColor(10, 25, 45);
  pdf.text(pdf.splitTextToSize(title, width), margin, y);
  y += 30;
  pdf.setFontSize(8);
  pdf.setTextColor(120);
  pdf.text(`Generated by JARVIS OS · ${new Date().toLocaleString()}`, margin, y);
  y += 24;

  for (const b of parseBlocks(content)) {
    const text = stripMd(b.text);
    if (!text && b.kind !== "table") continue;

    if (b.kind === "heading") {
      if (y > height - 80) { pdf.addPage(); y = margin; }
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(14);
      pdf.setTextColor(20, 60, 90);
      const lines = pdf.splitTextToSize(text, width);
      pdf.text(lines, margin, y);
      y += lines.length * 18 + 8;
    } else if (b.kind === "table" && b.rows) {
      pdf.setFont("courier", "normal");
      pdf.setFontSize(9);
      pdf.setTextColor(40);
      for (const row of b.rows) {
        const line = row.join("   |   ");
        if (y > height - 60) { pdf.addPage(); y = margin; }
        const lines = pdf.splitTextToSize(line, width);
        pdf.text(lines, margin, y);
        y += lines.length * 12 + 2;
      }
      y += 8;
    } else {
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);
      pdf.setTextColor(35);
      const lines = pdf.splitTextToSize(text, width);
      for (const line of lines) {
        if (y > height - margin) { pdf.addPage(); y = margin; }
        pdf.text(line, margin, y);
        y += 15;
      }
      y += 6;
    }
  }
  pdf.save(`${safeName(title)}.pdf`);
}

// ── Word (.docx) ─────────────────────────────────────────────────────────────

async function exportDocx(content: string, title: string): Promise<void> {
  const children: Paragraph[] = [
    new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun(title)] }),
    new Paragraph({ children: [new TextRun({ text: `Generated by JARVIS OS · ${new Date().toLocaleString()}`, italics: true, size: 16, color: "888888" })] }),
    new Paragraph({ text: "" }),
  ];

  for (const b of parseBlocks(content)) {
    const text = stripMd(b.text);
    if (b.kind === "heading") {
      children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun(text)] }));
    } else if (b.kind === "table" && b.rows) {
      for (const row of b.rows) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: row.join("  |  "), font: "Courier New", size: 18 })],
          })
        );
      }
      children.push(new Paragraph({ text: "" }));
    } else if (b.kind === "list") {
      for (const line of text.split("\n")) {
        children.push(new Paragraph({ text: line, bullet: { level: 0 } }));
      }
    } else if (text) {
      children.push(new Paragraph({ children: [new TextRun(text)], spacing: { after: 160 } }));
    }
  }

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, `${safeName(title)}.docx`);
}

// ── Excel (.xlsx) ────────────────────────────────────────────────────────────

function exportXlsx(content: string, title: string): void {
  const wb = XLSX.utils.book_new();
  const blocks = parseBlocks(content);
  const tables = blocks.filter((b) => b.kind === "table" && b.rows);

  if (tables.length > 0) {
    tables.forEach((t, i) => {
      const ws = XLSX.utils.aoa_to_sheet(t.rows!);
      XLSX.utils.book_append_sheet(wb, ws, `Table ${i + 1}`);
    });
  }
  // Always include the full text as a readable sheet.
  const textSheet = XLSX.utils.aoa_to_sheet(
    content.split("\n").map((line) => [stripMd(line)])
  );
  XLSX.utils.book_append_sheet(wb, textSheet, "Notes".slice(0, 28));

  const out = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  downloadBlob(
    new Blob([out], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `${safeName(title)}.xlsx`
  );
}

// ── Markdown / plain text ────────────────────────────────────────────────────

function exportTextFile(content: string, title: string, ext: "md" | "txt"): void {
  const header =
    ext === "md" ? `# ${title}\n\n> Generated by JARVIS OS · ${new Date().toLocaleString()}\n\n` : "";
  downloadBlob(
    new Blob([header + content], { type: "text/plain;charset=utf-8" }),
    `${safeName(title)}.${ext}`
  );
}

// ── Public API ───────────────────────────────────────────────────────────────

export const EXPORT_FORMATS: Array<{ id: ExportFormat; label: string }> = [
  { id: "pdf", label: "PDF" },
  { id: "docx", label: "Word" },
  { id: "xlsx", label: "Excel" },
  { id: "md", label: "Markdown" },
  { id: "txt", label: "Text" },
];

export async function exportDocument(content: string, title: string, format: ExportFormat): Promise<void> {
  switch (format) {
    case "pdf":
      return exportPdf(content, title);
    case "docx":
      return exportDocx(content, title);
    case "xlsx":
      return exportXlsx(content, title);
    case "md":
      return exportTextFile(content, title, "md");
    case "txt":
      return exportTextFile(content, title, "txt");
  }
}
